# ===================================================================
# PanelViewer — generic, extensible Makie window.
#
#   view_panels([panelset_a, panelset_b, ...])
#
# One window, one dropdown at the top. The dropdown selects which
# PanelSet is displayed; the layout logic below is completely generic
# over the panels in that set.
#
# THE POINT: this file contains no knowledge of any specific chart.
# It never mentions "solution comparison" or "cross-region" or
# "power series". To add a view you register a PanelSet (see
# Registry.jl) — you do not edit this file. That is what makes the
# views extendible.
#
# Because panel rendering is uniform (draw_panel! takes a
# GridPosition), switching sets is just "clear the grid and redraw",
# regardless of how many panels each set has or what kinds they are.
# ===================================================================

module PanelViewer

using GLMakie

include("Panels.jl")
using .Panels
using .Panels.PanelSpec

export view_panels

"""
    clear_layout!(gl::GridLayout)

Remove everything from `gl` so it can be reused for a different view.

Makie defines neither `empty!` nor `delete!` for `GridLayout`, only for
leaf `Block`s (Axis, Colorbar, Label, …). Panels legitimately nest —
a heatmap puts its Colorbar in a sub-layout, and a `:grid` panel is a
sub-layout by definition — so clearing has to recurse and delete only
the leaves. `trim!` then collapses the emptied rows/columns; without it
the next view inherits the previous one's sizing.
"""
function clear_layout!(gl::GridLayout)
  for child in reverse(collect(gl.content))
    c = child.content
    if c isa GridLayout
      clear_layout!(c)
    else
      delete!(c)
    end
  end
  trim!(gl)
  return gl
end

"""
    auto_layout(n) → (rows, cols)

Pick a near-square grid for `n` panels, preferring wider than tall
because screens are. Used when a PanelSet does not dictate its own
layout.
"""
function auto_layout(n::Int)
  n <= 0 && return (1, 1)
  n == 1 && return (1, 1)
  n == 2 && return (1, 2)
  cols = ceil(Int, sqrt(n))
  rows = ceil(Int, n / cols)
  return (rows, cols)
end

"""
    view_panels(sets; theme = nothing, size = (1600, 1000), initial = 1)

Open an interactive window over a list of `PanelSet`s.

- `sets`    — `Vector{PanelSet}`; the dropdown lists them by `name`
- `theme`   — optional theme object (see `Theme.jl`); `nothing` uses Makie defaults
- `initial` — index of the set shown first

Returns the `Figure` so callers can save or further decorate it.
"""
function view_panels(sets::Vector{<:PanelSpec.PanelSet};
                     theme = nothing, size = (1600, 1000), initial::Int = 1)
  isempty(sets) && error("view_panels: no PanelSets to display")
  initial = clamp(initial, 1, length(sets))

  bg = theme === nothing ? :white : GLMakie.to_color(theme.bg_primary)
  fg = theme === nothing ? :black : GLMakie.to_color(theme.text_primary)

  fig = Figure(size = size, backgroundcolor = bg)

  # ---- top bar: dropdown + provenance label ------------------------
  controls = GridLayout(fig[1, 1], tellwidth = false, tellheight = true)
  Label(controls[1, 1], "View:"; color = fg, fontsize = 15, halign = :right)

  names = [s.name for s in sets]
  menu = Menu(controls[1, 2]; options = names, default = names[initial],
              width = 320, tellwidth = false)

  info = Label(controls[1, 3], ""; color = fg, fontsize = 13, halign = :left)
  colsize!(controls, 3, Relative(0.55))

  # ---- panel area --------------------------------------------------
  # Held in its own GridLayout so switching views can wipe it wholesale
  # without disturbing the control bar.
  panel_area = fig[2, 1] = GridLayout()
  # Keep the control bar compact; Auto lets it claim a share of the
  # figure height and leaves a dead band above the panels.
  rowsize!(fig.layout, 1, Fixed(40))

  function describe(set)
    isempty(set.meta) && return "$(length(set.panels)) panels"
    bits = String[]
    for k in ("representation", "run_id", "source", "optimizer")
      haskey(set.meta, k) && push!(bits, "$k = $(set.meta[k])")
    end
    push!(bits, "$(length(set.panels)) panels")
    return join(bits, "   |   ")
  end

  # Blocks created by the current view. Legends (from axislegend) and
  # Colorbars attach to the Figure rather than to panel_area, so they are
  # invisible to clear_layout! and would survive a view switch as stale
  # duplicate entries. Tracking what each render actually created is the
  # only reliable way to remove all of it.
  drawn = Any[]

  function render!(set)
    # Wipe the previous view before drawing the next one.
    for b in reverse(drawn)
      b isa GridLayout && continue
      try
        delete!(b)
      catch
        # already removed as a child of a deleted parent — nothing to do
      end
    end
    empty!(drawn)
    clear_layout!(panel_area)
    before = Set(objectid.(fig.content))
    rows, cols = auto_layout(length(set.panels))
    for (i, panel) in enumerate(set.panels)
      r = div(i - 1, cols) + 1
      c = mod(i - 1, cols) + 1
      draw_panel!(panel_area[r, c], panel; theme = theme)
    end
    # Everything the panel renderers created, wherever it was attached.
    for b in fig.content
      objectid(b) in before || push!(drawn, b)
    end
    info.text = describe(set)
    return nothing
  end

  render!(sets[initial])

  on(menu.selection) do sel
    sel === nothing && return
    idx = findfirst(==(sel), names)
    idx === nothing && return
    render!(sets[idx])
  end

  display(fig)
  return fig
end

# Convenience: accept a single set without wrapping it in a vector.
view_panels(set::PanelSpec.PanelSet; kwargs...) =
  view_panels([set]; kwargs...)

"""
    view_panels(paths::Vector{String}; kwargs...)

Load PanelSets from JSON files written by `PanelSpec.save_panels` and
display them. This is how experiment output becomes a view without any
code change.
"""
view_panels(paths::Vector{String}; kwargs...) =
  view_panels([PanelSpec.load_panels(p) for p in paths]; kwargs...)

end # module PanelViewer
